blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/souravs72/claude-mcp-setup/discussions
    about: Ask questions and discuss ideas with the community
  - name: Security Vulnerability
    url: https://github.com/souravs72/claude-mcp-setup/security/advisories/new
    about: Report security vulnerabilities privately
