{{- if .Values.servers.github.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-server
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.servers.github.replicas }}
  selector:
    matchLabels:
      app: github-server
  template:
    metadata:
      labels:
        app: github-server
    spec:
      containers:
      - name: github-server
        image: {{ .Values.global.imageRegistry }}/github:{{ .Values.global.imageTag }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: 8003
          name: http
        env:
        - name: GITHUB_PERSONAL_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: mcp-secrets
              key: github-token
        resources:
          {{- toYaml .Values.servers.github.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: github-service
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.servers.github.service.type }}
  selector:
    app: github-server
  ports:
  - port: {{ .Values.servers.github.service.port }}
    targetPort: 8003
    protocol: TCP
{{- end }}

