{{- if .Values.servers.goalAgent.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goal-agent-server
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.servers.goalAgent.replicas }}
  selector:
    matchLabels:
      app: goal-agent-server
  template:
    metadata:
      labels:
        app: goal-agent-server
    spec:
      containers:
      - name: goal-agent-server
        image: {{ .Values.global.imageRegistry }}/goal-agent:{{ .Values.global.imageTag }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: 8002
          name: http
        env:
        - name: POSTGRES_HOST
          value: {{ .Values.servers.goalAgent.env.POSTGRES_HOST | quote }}
        - name: POSTGRES_PORT
          value: {{ .Values.servers.goalAgent.env.POSTGRES_PORT | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.servers.goalAgent.env.POSTGRES_DB | quote }}
        - name: POSTGRES_USER
          value: {{ .Values.servers.goalAgent.env.POSTGRES_USER | quote }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mcp-secrets
              key: postgres-password
        - name: REDIS_HOST
          value: {{ .Values.servers.goalAgent.env.REDIS_HOST | quote }}
        - name: REDIS_PORT
          value: {{ .Values.servers.goalAgent.env.REDIS_PORT | quote }}
        - name: GOAL_AGENT_MAX_WORKERS
          value: {{ .Values.servers.goalAgent.env.GOAL_AGENT_MAX_WORKERS | quote }}
        - name: CACHE_ENABLED
          value: {{ .Values.servers.goalAgent.env.CACHE_ENABLED | quote }}
        resources:
          {{- toYaml .Values.servers.goalAgent.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: goal-agent-service
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.servers.goalAgent.service.type }}
  selector:
    app: goal-agent-server
  ports:
  - port: {{ .Values.servers.goalAgent.service.port }}
    targetPort: 8002
    protocol: TCP
{{- end }}

