{{- if .Values.servers.internet.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: internet-server
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.servers.internet.replicas }}
  selector:
    matchLabels:
      app: internet-server
  template:
    metadata:
      labels:
        app: internet-server
    spec:
      containers:
      - name: internet-server
        image: {{ .Values.global.imageRegistry }}/internet:{{ .Values.global.imageTag }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: 8005
          name: http
        env:
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: mcp-secrets
              key: google-api-key
        - name: GOOGLE_SEARCH_ENGINE_ID
          valueFrom:
            secretKeyRef:
              name: mcp-secrets
              key: google-search-engine-id
        resources:
          {{- toYaml .Values.servers.internet.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /health
            port: 8005
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8005
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: internet-service
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.servers.internet.service.type }}
  selector:
    app: internet-server
  ports:
  - port: {{ .Values.servers.internet.service.port }}
    targetPort: 8005
    protocol: TCP
{{- end }}

