{{- if .Values.servers.memoryCache.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-cache-server
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.servers.memoryCache.replicas }}
  selector:
    matchLabels:
      app: memory-cache-server
  template:
    metadata:
      labels:
        app: memory-cache-server
    spec:
      containers:
      - name: memory-cache-server
        image: {{ .Values.global.imageRegistry }}/memory-cache:{{ .Values.global.imageTag }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: 8001
          name: http
        env:
        - name: REDIS_HOST
          value: {{ .Values.servers.memoryCache.env.REDIS_HOST | quote }}
        - name: REDIS_PORT
          value: {{ .Values.servers.memoryCache.env.REDIS_PORT | quote }}
        resources:
          {{- toYaml .Values.servers.memoryCache.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: memory-cache-service
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.servers.memoryCache.service.type }}
  selector:
    app: memory-cache-server
  ports:
  - port: {{ .Values.servers.memoryCache.service.port }}
    targetPort: 8001
    protocol: TCP
{{- end }}

