{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    app: mcp-servers
    environment: {{ .Values.environment | default "production" }}
{{- end }}

