apiVersion: v1
kind: Secret
metadata:
  name: mcp-secrets
  namespace: mcp-servers
type: Opaque
stringData:
  github-token: {{ .Values.secrets.githubToken | quote }}
  jira-token: {{ .Values.secrets.jiraApiToken | quote }}
  google-api-key: {{ .Values.secrets.googleApiKey | quote }}
  google-search-engine-id: {{ .Values.secrets.googleSearchEngineId | quote }}
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
