name: Auto PR from dev to main (CLI)

on:
  push:
    branches: [dev]

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        run: |
          # Check if PR already exists
          if gh pr list --base main --head dev --json number --jq 'length' | grep -q "0"; then
            gh pr create \
              --base main \
              --head dev \
              --title "🚀 Merge dev to main - ${{ github.event.head_commit.message }}" \
              --body "## Changes from dev branch
              
          This PR was automatically created from the dev branch.
          
          **Commit:** ${{ github.event.head_commit.message }}
          **Author:** ${{ github.event.head_commit.author.name }}
          **Date:** ${{ github.event.head_commit.timestamp }}
          
          ### What's Changed
          - Latest updates from dev branch
          - Ready for review and merge
          
          ### Checklist
          - [ ] Code reviewed
          - [ ] Tests passing
          - [ ] Documentation updated" \
              --label "auto-merge,dev-to-main" \
              --assignee "${{ github.event.head_commit.author.name }}"
          else
            echo "PR already exists from dev to main"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
